# Generated by Django 4.1.13 on 2025-05-14 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerUsageArchive',
            fields=[
                ('counter', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_year', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerUsageBuffer',
            fields=[
                ('counter', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_year', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PastComputerRecords',
        ),
    ]
